export { default as main } from './main.web'
export { default as cv } from './cv.web'
export { default as blog } from './blog.web'
export { default as books } from './books.web'
export { default as about } from './about.web'